CREATE TABLE CON(
	CID	INT IDENTITY(1,1) PRIMARY KEY,
	Name	NVARCHAR(128) NOT NULL
);

CREATE TABLE MERCH(
	PID	INT IDENTITY(1,1) PRIMARY KEY,
	Name	NVARCHAR(128) NOT NULL,
	Image	NVARCHAR(128),
	Siz	TINYINT NOT NULL FOREIGN KEY REFERENCES PRICE(Siz),
	forsale	BIT NOT NULL,
	nsfw	BIT NOT NULL,
	quantity	SMALLINT
);

CREATE TABLE SALE(
	RID	INT IDENTITY(1,1) PRIMARY KEY,
	Thetime	DATETIME NOT NULL,
	CID	INT NOT NULL FOREIGN KEY REFERENCES CON(CID),
	Total	MONEY
);

CREATE TABLE SUBSALE(
	RID INT NOT NULL FOREIGN KEY REFERENCES SALE(RID),
	PID INT NOT NULL FOREIGN KEY REFERENCES MERCH(PID)
);

CREATE TABLE PRICE(
	Siz	TINYINT IDENTITY(1,1) PRIMARY KEY,
	Sizlong	NVARCHAR(32),
	Cost	MONEY
);